@baseUrl=http://localhost:3000/api/users
@idUserFind=6a868c390d22f35f4e379049
@idUserDelete=6a2ced4832ce6874459710cc

### get all users
GET {{baseUrl}}

### get user by id
GET {{baseUrl}}/{{idUserFind}}

### delete user
DELETE {{baseUrl}}/{{idUserDelete}}