
@idUserFind=6a7f8d87d04068b08abd6058
@idUserDelete=6a2ced4832ce6874459710cc

### delete all users
GET http://localhost:3000/api/delete

### get all users
GET http://localhost:3000/api/user

### get user by id
GET http://localhost:3000/api/user/{{idUserFind}}

### delete user
DELETE http://localhost:3000/api/user/{{idUserDelete}}