### register user
POST  http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "David Sliren",
    "username": "jhojan12", 
    "relationship": "hijo",
    "tel": "3044518133",
    
    "password": "Jojojo12"
}

### login user

POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
    "username": "sliren",
    "password": "Jojojo12"
}

### logout user
POST http://localhost:3000/api/auth/logout 
Content-Type: application/json