@baseUrl=http://localhost:3000/api/dashboard/patient
@userId="6a751b35960fabe64b8a19d2"
### default 
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "David",
    "lastName": "salazar",
    "age": 22,
    "reason": "medicamentos",
    "userId": {{userId}},
    "description": "esta en el hospital santa barbara y neceitamos recaudar dinero para los medicamentos",
    "monthlyGoal": 200000
}