import "./globals.css";
import { bodyFont } from "@/config/fonts";

export const metadata = {
  title: "Aleida | Contribucion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${bodyFont.variable} h-full antialiased scroll-hiden`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
