@baseUrl=http://localhost:3000/api/dashboard/expenses
@access-Token=access-token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjZhN2U3NzAzNDQ3MWQ0M2JkMzc0YmM1YSIsInVzZXJuYW1lIjoic2xpcmVuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzg2NzU4NTY5LCJleHAiOjE3ODY3NjU3Njl9.aCzPaD8JAtXe_0qiQ4odL4MP7LkuYzPf8Db1fByzkjY
@patientId="6a7f8dffd04068b08abd6059"

###
POST {{baseUrl}}
Cookie: {{access-Token}}
Content-Type: application/json

{
    "name": "taxi",
    "amount": 100000,
    "currency": "COP",
    "category": "transporte",
    "patientId": {{patientId}}
}
