@baseUrl=http://localhost:3000/api/dashboard/expenses
@access-Token=access-token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjZhNzUxYjM1OTYwZmFiZTY0YjhhMTlkMiIsInVzZXJuYW1lIjoiamhvamFuMTIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3ODYxMzgzMTAsImV4cCI6MTc4NjE0NTUxMH0.lQRNRhu4mn6qAYODvtyhcAjsuDZIfTqHFNJc3AKMXpc
@expenseId=
@patientId="6a751bb8ebf2c45726716633"
@createBy="6a751bb8ebf2c45726716633"
###
PUT  {{baseUrl}}/{{expenseId}}
Cookie: {{access-Token}}
Content-Type: application/json

{
    "name": "ambulancia",
    "amount": 250000,
    "currency": "COP",
    "category": "transporte",
    "patientId": {{patientId}},
    "createBy": {{createBy}}
}
